name: solidui_example
description: A simple example demonstrating SolidScaffold usage.
publish_to: 'none'
version: 0.0.4+0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  markdown_tooltip: any
  shared_preferences: ^2.5.3
  # solidpod: ^0.7.14
  solidpod:
    git:
      url: https://github.com/anusii/solidpod.git
      ref: tony/467_migrate_loginIfRequired_and_getKeyFromUserIfRequired
  # solidui: ^0.0.4
  solidui:
    git:
      url: https://github.com/anusii/solidui.git
      ref: tony/467_migrate_loginIfRequired_and_getKeyFromUserIfRequired
  window_manager: ^0.4.3

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
