name: demopod
description: 'A SolidUI Demonstrator.'
publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  editable: ^2.0.0
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  markdown_tooltip: ^0.0.10
  rdflib: ^0.2.12
  solidpod: ^1.0.6
  solidui:
    path: ..
  universal_io: ^2.3.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^6.0.0

dependency_overrides:
  solidpod:
    # path: ../solidpod
    git:
      url: https://github.com/anusii/solidpod.git
      ref: tony/622_save_large_files_to_external_pod

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
  assets:
    - assets/images/
