name: myapp
description: My App - A SolidUI Template Application
publish_to: 'none'
version: 0.0.4+0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  markdown_tooltip: 0.0.10
  shared_preferences: ^2.5.4
  solidpod: ^0.10.1
  solidui: # ^0.1.0
    path: ..
  window_manager: ^0.5.1

dependency_overrides:
  solidpod:
    git:
      url: https://github.com/anusii/solidpod.git
      ref: tony/127_browserpod
  solidui:
    path: ..

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
