name: solidui
description: "A UI library for building Solid applications with Flutter."
publish_to: "none"
version: 0.0.2

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.2
  flutter_markdown: ^0.7.7+1
  gap: ^3.0.1
  markdown_tooltip: ^0.0.8
  package_info_plus: ^8.3.1
  path: ^1.9.1
  rdflib: ^0.2.12
  shared_preferences: ^2.3.3
  solidpod: ^0.7.8
  url_launcher: ^6.3.1
  version_widget: ^1.0.4

dev_dependencies:
  flutter_lints: ^5.0.0
  window_manager: ^0.5.1

flutter:
  uses-material-design: true
