name: solidui
description: 'A UI library for building Solid applications with Flutter.'
version: 1.0.7
homepage: https://github.com/anusii/solidui

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.44.0'

# To automatically upgrade package dependencies to the latest versions:
#
#   flutter pub upgrade --major-versions
#
# To see which dependencies have newer versions available:
#
#   flutter pub outdated

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^11.0.2
  flutter_form_builder: ^10.3.0+1
  flutter_markdown_plus: ^1.0.7
  form_builder_validators: ^11.3.0
  gap: ^3.0.1
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  markdown_tooltip: ^0.0.10
  package_info_plus: ^9.0.0
  path: ^1.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  rdflib: ^0.2.12
  share_plus: ^11.0.0
  shared_preferences: ^2.5.4
  solidpod: ^1.0.6
  universal_io: ^2.3.1
  url_launcher: ^6.3.2
  version_widget: ^1.0.10

dev_dependencies:
  flutter_lints: ^6.0.0
  window_manager: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
